scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['https://d1gs7x7eyzx088.cloudfront.net:8080']
        labels:
          application: 'My Spring Boot Application'