# You will need to use type: LoadBalancer so that the frontend can hit the API when loaded in the browser

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.fwdPort}}
      targetPort: {{.Values.appPort}}
  type: {{.Values.serviceType}}
