# You will need to use type: LoadBalancer so that the frontend can hit the API when loaded in the browser

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  namespace: default
  annotations:
    prometheus.io/port: {{.Values.portName}}
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/metrics
  labels:
    app.kubernetes.io/part-of: {{.Values.appName}}

spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.fwdPort}}
      targetPort: {{.Values.appPort}}
      name: {{.Values.portName}}
  type: {{.Values.serviceType}}
