apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api-service-monitor
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      port: {{.Values.portName}}
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{.Values.appName}}
