# You will need to use type: LoadBalancer so that the frontend can hit the API when loaded in the browser

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  namespace: default
  annotations:
    prometheus.io/port: {{.Values.metricsPort}}
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
  labels:
    app.kubernetes.io/part-of: {{.Values.appName}}

spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - port: {{.Values.fwdPort}}
      name: {{.Values.portName}}
      protocol: TCP
      targetPort: {{.Values.appPort}}
    - port: 9000
      targetPort: {{.Values.appPort}}
      name: {{.Values.metricsPort}}
      protocol: TCP
  type: {{.Values.serviceType}}
